

# For more configuration details:
# https://docs.codecov.io/docs/codecov-yaml

# Check if this file is valid by running in bash:
# curl -X POST --data-binary @.codecov.yml https://codecov.io/validate

# Coverage configuration
# ----------------------
coverage:
  status:
    patch: false

  range: 70..90     # First number represents red, and second represents green
                    # (default is 70..100)
  round: up       # up, down, or nearest
  precision: 2      # Number of decimal places, between 0 and 5

# Ignoring Paths
# --------------
# which folders/files to ignore
# Ignoring for now until we can include them in workspace
ignore:
  - arkworks/benchmarks/*/**
  - arkworks/plonk-circuits/*/**
  - arkworks/plonk-gadgets/*/**

# Pull request comments:
# ----------------------
# Diff is the Coverage Diff of the pull request.
# Files are the files impacted by the pull request
# comment:
#   layout: diff, files # - accepted in any order: reach, diff, flags, and/or files