name: checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set-Up
        run: ./scripts/init.sh

      - name: Fmt Check
        run: ./scripts/fmt-check.sh

      - name: Clippy Check
        run: ./scripts/clippy.sh

      - name: Build
        run: ./scripts/build.sh

      - name: Wasm Build
        run: ./scripts/build-wasm.sh

      - name: Test
        run: ./scripts/test.sh
